# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313bf7ef2e7411145e00a33a3f9b4a52258e45ee9ed6836eabab6d10b946738270845d4a6a93213c2916c68a11268bb83d0ca64d1a82a2ea8fbefd41f32d0f2d

test:
  secret_key_base: 26bf1f9208937b028ff2752b7dead89f14effe2b5fb1d1c40ffca24d160a0fb85097b68ade4022a271b0bbd6038fc722c39d1cd87d22435df07367e9230bebff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
